### ISSUE TITLE
Chapter 1 最後一段試譯

### ISSUE THREAD

**Issue by DuPupu** [NawaShoLin/SICP-zh-tw#2]
既然Lisp並非主流語言，為什麼本書還要以其作為討論程式設計的框架呢？Lisp擁有的獨特的特性使其成為一門優秀的學習重要的程式設計基礎和數據結構的媒介，並能將其與Lisp的語言特性緊密結合。其中最重要的特性是，所謂的procedure，即以Lisp語言描述的過程，自身可以作為Lisp數據而被表現和操作。個中的重要性是，強大的程式設計方法可以模糊傳統觀念上被動的數據和主動的過程之間的界限。正如我們將要發現的，Lisp如數據一半處理過程的靈活性使得之成為探索這些方法的最便捷的語言之一。將過程表現為數據的特性亦使得Lisp可以寫出將其他程式視為數據並進行操作的程式，如處理其它計算機語言的解釋器和編譯器，而成為一門傑出的程式設計語言。綜上所述，餘不一一，用Lisp編寫程式充滿樂趣。

**Comment by NawaShoLin** [comment]
Thanks. You can use pull request. I'll merge it :)
